apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  labels:
    app.kubernetes.io/instance: test-chatbot-evan
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-chatbot-evan
    app.kubernetes.io/part-of: test-chatbot-evan
  name: test-chatbot-evan
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-chatbot-evan
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test-chatbot-evan
    spec:
      containers:
        - image: quay.io/tpetkos/test-chatbot-evan:ae3cbe3dd59f894ec7f140a569b3ec729edeaae5@sha256:95ca74c38f86071b45750e70f014634fbeca43308c0e108bbab5b2febd8e1b14
          name: app-inference
          envFrom:
            - configMapRef:
                name: test-chatbot-evan-model-config
          ports:
            - containerPort: 8501
          securityContext:
            runAsNonRoot: true
