apiVersion: v1
kind: ConfigMap
metadata:
  name: test-chatbot-evan-model-config
data:
  MODEL_ENDPOINT: "https://granite-7b-starter-140-version-1.rolling-demo-ns.svc.cluster.local"
  MODEL_NAME: "granite-7b-starter-140-version-1"
